-- 0007_agent_review_job.sql — (registry rows moved to db/seed/jobs.seed.sql)
--
-- ORIGINALLY this migration INSERTed the agent-review ops.jobs registry row and
-- flipped the PG-writer jobs to monitored=true, so agent-review could satisfy the
-- ops.job_runs.job_name -> ops.jobs.name FK and the doctor's liveness moved onto
-- ops.job_runs (auto-review-hg6.8). Those rows named an internal deploy host, so
-- per auto-review-6mf.2 and the infra/content-separation epic the ops.jobs
-- REGISTRY is no longer populated from committed SQL:
--   * mechanism (this migration + the ops.jobs table in 0001) stays in the repo;
--   * content (the rows: host, cadence, monitored flags, expected_interval) is
--     seeded at APPLY TIME from the gitignored db/seed/jobs.seed.sql — sanitized
--     shape in db/seed/jobs.seed.example.sql — mirroring the projects seed.
-- See docs/superpowers/specs/2026-06-30-jobs-registry-pg.md (and its parent
-- 2026-06-27-infra-content-separation-design.md).
--
-- APPLY ORDER (design note, decision 3): migrate.sh (this file is a recorded
-- no-op) -> apply db/seed/jobs.seed.sql -> first job run. A job that writes
-- ops.job_runs before its seed row exists hits the FK, but that write is
-- best-effort and degrades to a no-op (db/README.md), so the ordering is a
-- correctness SHOULD, not a crash.
--
-- MIGRATION-HISTORY CAVEAT: rows a PRIOR migrate.sh run already committed to a
-- live DB stay put — removing the INSERT/UPDATE here does not un-apply them, and
-- migrate.sh skips already-recorded versions so it will not re-run this file.
-- This change only stops committing NEW content rows; the live registry is
-- reconciled by (idempotently) applying jobs.seed.sql.
--
-- Kept as a recorded (no-op) migration so the runner's filename ordering and
-- ops.schema_migrations history stay unbroken (db/verify.sh asserts each file is
-- recorded). The ops.jobs TABLE definition lives in 0001 and is unchanged.
