-- 0008_vault_review_jobs.sql — (registry rows moved to db/seed/jobs.seed.sql)
--
-- ORIGINALLY this migration INSERTed the vault-review daily and weekly ops.jobs
-- registry rows, finishing the doctor's exit from the cron.log-commit + marker
-- liveness path onto ops.job_runs (auto-review-2vv / hg6.8). Those rows named an
-- internal deploy host and the exact fire schedule, so per auto-review-6mf.2 and
-- the infra/content-separation epic the ops.jobs REGISTRY is no longer populated
-- from committed SQL: the rows are seeded at APPLY TIME from the gitignored
-- db/seed/jobs.seed.sql (sanitized shape in db/seed/jobs.seed.example.sql),
-- mirroring the projects registry seed. See
-- docs/superpowers/specs/2026-06-30-jobs-registry-pg.md.
--
-- NOTE (weekly liveness): the weekly job's expected_interval in the seed is only
-- a registry/FK sanity bound; a flat age window can't monitor a weekly cron (a
-- real miss stays green for ~a week; a tight window false-positives before each
-- fire). The SCHEDULE-AWARE weekly check lives in the doctor's code, not in the
-- row — see the design note, decision 1 (liveness mechanics live in code).
--
-- APPLY ORDER (design note, decision 3): migrate.sh (this file is a recorded
-- no-op) -> apply db/seed/jobs.seed.sql -> first job run. A run-row written
-- before its seed row exists hits the FK, but that write is best-effort and
-- degrades to a no-op (db/README.md), so the ordering is a correctness SHOULD.
--
-- MIGRATION-HISTORY CAVEAT: rows a PRIOR migrate.sh run already committed to a
-- live DB stay put — removing the INSERTs here does not un-apply them, and
-- migrate.sh skips already-recorded versions so it will not re-run this file.
-- This change only stops committing NEW content rows; the live registry is
-- reconciled by (idempotently) applying jobs.seed.sql.
--
-- Kept as a recorded (no-op) migration so the runner's filename ordering and
-- ops.schema_migrations history stay unbroken. The ops.jobs TABLE lives in 0001.
