-- 0009_auto_review_doctor_job.sql — (registry row moved to db/seed/jobs.seed.sql)
--
-- ORIGINALLY this migration INSERTed the auto-review-doctor ops.jobs registry row
-- so the doctor could record its OWN ops.job_runs row each run — the external
-- dead-man substrate (auto-review-02w): "latest doctor row age" is a queryable
-- who-watches-the-watcher signal any independent process can check with
--   SELECT now() - max(finished_at) FROM ops.job_runs WHERE job_name = 'auto-review-doctor';
-- The row named an internal deploy host, so per auto-review-6mf.2 and the
-- infra/content-separation epic the ops.jobs REGISTRY is no longer populated from
-- committed SQL: it is seeded at APPLY TIME from the gitignored
-- db/seed/jobs.seed.sql (sanitized shape in db/seed/jobs.seed.example.sql). See
-- docs/superpowers/specs/2026-06-30-jobs-registry-pg.md.
--
-- APPLY ORDER (design note, decision 3): migrate.sh (this file is a recorded
-- no-op) -> apply db/seed/jobs.seed.sql -> first doctor run. The doctor's
-- self-row write BEFORE its seed row exists hits the FK, but that write is
-- best-effort and degrades to a no-op (db/README.md — it "never crashes the
-- health output"), so the ordering is a correctness SHOULD, not a crash.
--
-- MIGRATION-HISTORY CAVEAT: a row a PRIOR migrate.sh run already committed to a
-- live DB stays put — removing the INSERT here does not un-apply it, and
-- migrate.sh skips already-recorded versions so it will not re-run this file.
-- This change only stops committing NEW content rows; the live registry is
-- reconciled by (idempotently) applying jobs.seed.sql.
--
-- Kept as a recorded (no-op) migration so the runner's filename ordering and
-- ops.schema_migrations history stay unbroken. The ops.jobs TABLE lives in 0001;
-- the auto_review_doctor role already holds INSERT on ops.job_runs (0005).
